// web-next/pages/index.tsx
import type { NextPage } from 'next';
import { getClient } from '@/lib/sanity';
import { groq } from 'next-sanity';
import { Banner } from '@/components/Banner';
import { PostCard } from '@/components/Blog/PostCard';
import { Post } from '@/types';

interface Props {
  posts: Array<Post>;
}

export async function getStaticProps() {
  const query = groq`*[_type == "post" && !(_id in path('drafts.**'))] | order(_createdAt asc)`;

  const client = getClient(false);

  const posts = await client.fetch(query);

  return {
    props: {
      posts,
    },
  };
}

const Home: NextPage = (props) => {
  return (
    <>
      <Banner heading="Mujaj dev" subheading="Welcome to:">
        <p className="p-sm">
          A blog / portofolio for my own creations within{' '}
          <span className="border-primary inline-flex border-b-4 leading-tight">
            development
          </span>{' '}
          and{' '}
          <span className="border-primary inline-flex border-b-4 leading-tight">
            photography
          </span>
          .
        </p>
      </Banner>
      {props.posts.length > 0 && (
        <section className="mx-auto pt-10">
          <h2 className="mb-4 text-3xl font-bold">Latests Posts</h2>
          <ul className="grid grid-cols-[1fr_1fr] items-stretch gap-8">
            {props.posts.map((post) => (
              <li key={post._id}>
                <PostCard post={post} />
              </li>
            ))}
          </ul>
        </section>
      )}
    </>
  );
};

export default Home;

// web/src/pages/Index.vue
<template>
  <Layout>
    <app-banner heading="Mujaj dev" subheading="Welcome to:">
      <p class="p-sm">
        A blog / portofolio for my own creations within
        <span class="inline-flex border-b-4 border-primary leading-tight">development</span> and
        <span class="inline-flex border-b-4 border-primary leading-tight">photography</span>.
      </p>
    </app-banner>
    <section v-if="$page.posts.edges.length" class="mx-auto pt-10">
      <h2 class="font-bold mb-4 text-3xl">Latests Posts</h2>
      <post-list :posts="$page.posts.edges" />
    </section>
    <section v-if="$page.projects.edges.length" class="mx-auto pt-10">
      <h2 class="font-bold mb-4 text-3xl">Latest Project</h2>
      <project-list :projects="$page.projects.edges" />
    </section>
    <section v-if="$page.collections.edges.length" class="mx-auto pt-10">
      <h2 class="font-bold mb-4 text-3xl">Latest Collections</h2>
      <div>{{ $page.collections.edges[0].node.title }}</div>
    </section>
  </Layout>
</template>

<page-query>
{
  metadata {
    sanityOptions {
      projectId
      dataset
    }
  }
  posts: allSanityPost(sortBy: "publishedAt") {
    edges {
      node {
        id
        slug {
          current
        }
        title
        publishedAt(format: "MMMM D, YYYY")
        mainImage {
          asset {
            id
            localFile(width: 660, quality: 80)
            url
          }
        }
        authors {
          author {
            name
          }
        }
      }
    }
  }
  projects: allSanityProject (sortBy: "completed" limit: 1) {
    edges {
      node {
        id
        slug {
          current
        }
        title
        mainImage {
          asset {
            id
            localFile(width: 1100, quality: 80)
            url
          }
        }
      }
    }
  }
  collections: allSanityPhotoCollection (sortBy: "publishedAt" limit: 1) {
    edges {
      node {
        id
        slug {
          current
        }
        title
      }
    }
  }
}

</page-query>

<script>
import AppBanner from '@/components/AppBanner.vue';
import PostList from '@/components/Blog/PostList.vue';
import ProjectList from '@/components/Project/ProjectList.vue';

export default {
  components: {
    AppBanner,
    PostList,
    ProjectList,
  },

  metaInfo: {
    title: 'Hello, world!',
  },
};
</script>
